version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: osticket-mysql
    hostname: mysql
    ports:
        - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=secret
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']

  osticket:
    build: .
    container_name: osticket
    hostname: osticket
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3003:80"

